# Generated by Django 5.0.6 on 2024-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'booking_status',
                'managed': False,
            },
        ),
    ]
