# Generated by Django 5.0.6 on 2024-06-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('airplaneid', models.AutoField(primary_key=True, serialize=False)),
                ('airplanename', models.CharField(blank=True, max_length=100, null=True)),
                ('airplanecode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'airplanes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airportid', models.AutoField(primary_key=True, serialize=False)),
                ('airportname', models.CharField(blank=True, max_length=100, null=True)),
                ('airportcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('bookingdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, max_length=100, null=True)),
                ('citycode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flightid', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'flights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('genderid', models.AutoField(primary_key=True, serialize=False)),
                ('gendername', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passengerid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('passportnumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'passengers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeid', models.AutoField(primary_key=True, serialize=False)),
                ('flightduration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
